"""add_operating_hours_table

Revision ID: 167c7cd9f5a0
Revises: 4c2d9ee5ca61
Create Date: 2026-08-02 17:04:34.617977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167c7cd9f5a0'
down_revision = '4c2d9ee5ca61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operating_hours',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_hours_id'), 'operating_hours', ['id'], unique=False)
    op.create_index(op.f('ix_operating_hours_restaurant_id'), 'operating_hours', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operating_hours_restaurant_id'), table_name='operating_hours')
    op.drop_index(op.f('ix_operating_hours_id'), table_name='operating_hours')
    op.drop_table('operating_hours')
    # ### end Alembic commands ###
